version: "3.7"
services:
    ksiemgowyd:
        build:
            context: .
        volumes:
            - "./db_public:/db_public"
        restart: unless-stopped
        secrets:
            - deploy_key
secrets:
    deploy_key:
        file: homepage_deploykey
