version: "3.7"
services:
    ksiemgowyd:
        build:
            context: .
        env_file:
            - envfile_secret
            - envfile_public
        environment:
            DEPLOY_KEY_PATH: /run/secrets/deploy_key
        volumes:
            - "./db_private:/db_private"
            - "./db_public:/db_public"
        restart: unless-stopped
        secrets:
            - deploy_key
secrets:
    deploy_key:
        file: homepage_deploykey
