DEPLOY_KEY_PATH: ""
HOMEPAGE_GIT_REPO_URL: ""
DUES_FILE_PATH: ""
DATABASE_URI: ""
MBANK_ANONYMIZATION_KEY: ""
SEND_MAIL: true
GRAPHITE_HOST: ""
GRAPHITE_PORT: 31337
ACCOUNTS:
    - IMAP_LOGIN: ""
      IMAP_SERVER: ""
      IMAP_PASSWORD: ""
      IMAP_FILTER: ""
      ACC_NO: ""
