name: ksiemgowy

on:
    - push

jobs:
    unittest_and_docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt
            - name: Run unit tests and generate coverage
              run: |
                  COVERAGE_PATH=$(python -c 'print(__import__("importlib").util.find_spec("coverage").origin)' | xargs dirname)
                  find $COVERAGE_PATH -name index.html | grep htmlfiles | xargs -n1 sed '/created/d' -i
                  find $COVERAGE_PATH -name pyfile.html | grep htmlfiles | xargs -n1 sed '/created/d' -i
                  python -m coverage run --source=ksiemgowy --branch -m unittest -v
                  python -m coverage html
                  rm -rf docs/htmlcov
                  mv htmlcov docs
            - name: regenerage docs
              run: cd docs/_sphinx && make
            - uses: stefanzweifel/git-auto-commit-action@v4.2.0
              with:
                  commit_message: Autoupdate code coverage stats

    flake8:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt
            - name: Lint with flake8
              run: |
                  flake8 --ignore=W503 ksiemgowy/

    pylint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt
            - name: Pylint code analysis
              run: |
                  pylint ksiemgowy/

    mypy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt
            - name: MyPy code analysis
              run: |
                  mypy --strict ksiemgowy
                  mypy --config-file=/dev/null test
