name: ksiemgowy

on:
  - push
  - pull_request

jobs:
  flake8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ksiemgowyd.txt
        pip install -r requirements-web.txt
    - name: Lint with flake8
      run: |
        python -m pip install flake8
        flake8 ksiemgowy/
        flake8 ksiemgowy-web.py

  pylint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ksiemgowyd.txt
        pip install -r requirements-web.txt
    - name: Pylint code analysis
      run: |
        python -m pip install pylint
        pylint ksiemgowy/
        pylint ksiemgowy-web.py
